name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk, 20-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --stacktrace --warning-mode fail
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Test Reports
          path: build/reports/